/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gcj_jni_HelloJNI */

#ifndef _Included_com_gcj_jni_HelloJNI
#define _Included_com_gcj_jni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gcj_jni_HelloJNI
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gcj_jni_HelloJNI_get
  (JNIEnv *, jclass);

/*
 * Class:     com_gw_jni_HelloJNI
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_gcj_jni_HelloJNI_set
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
